# Exercise 1: Your first DataFrame

The model DataFrame is created in two ways:

- from a NumPy array
- from Pandas Series

In [1]:
import numpy as np
import pandas as pd

index = [1, 3, 5, 7, 9]

array_data = np.array(
    [
        ["Blue", [1, 2], 1.1],
        ["Red", [3, 4], 2.2],
        ["Pink", [5, 6], 3.3],
        ["Grey", [7, 8], 4.4],
        ["Black", [9, 10], 5.5],
    ],
    dtype=object,
)

df_from_array = pd.DataFrame(array_data, columns=["color", "list", "number"], index=index)
df_from_array = df_from_array.astype({"number": "float64"})
df_from_array

   color     list  number
1   Blue   [1, 2]     1.1
3    Red   [3, 4]     2.2
5   Pink   [5, 6]     3.3
7   Grey   [7, 8]     4.4
9  Black  [9, 10]     5.5

In [2]:
series_data = {
    "color": pd.Series(["Blue", "Red", "Pink", "Grey", "Black"], index=index),
    "list": pd.Series([[1, 2], [3, 4], [5, 6], [7, 8], [9, 10]], index=index),
    "number": pd.Series([1.1, 2.2, 3.3, 4.4, 5.5], index=index, dtype="float64"),
}

df_from_series = pd.DataFrame(series_data)
df_from_series

   color     list  number
1   Blue   [1, 2]     1.1
3    Red   [3, 4]     2.2
5   Pink   [5, 6]     3.3
7   Grey   [7, 8]     4.4
9  Black  [9, 10]     5.5

In [3]:
df_from_array.equals(df_from_series)

True

In [4]:
df = df_from_array.copy()

for column in df.columns:
    print(type(df[column]))

for column in df.columns:
    print(type(df[column].iloc[0]))

<class 'pandas.Series'>
<class 'pandas.Series'>
<class 'pandas.Series'>
<class 'str'>
<class 'list'>
<class 'numpy.float64'>